sudo: required
services:
  - docker

before_install:
  - docker build -t jablesyeah/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true jablesyeah/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-course"
  env: "docker-course"
  bucket_name: "elasticbeanstalk-eu-west-2-133775116748"
  bucket_path: "docker-course" #same as app name
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

# docker-course.eba-mm932r4f.eu-west-2.elasticbeanstalk.com